//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NScrape {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NScrapeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NScrapeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NScrape.NScrapeResources", typeof(NScrapeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  NScrape/{0} (+https://github.com/darrylwhitmore/NScrape).
        /// </summary>
        internal static string DefaultUserAgent {
            get {
                return ResourceManager.GetString("DefaultUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form {0} &apos;{1}&apos; was not found..
        /// </summary>
        internal static string InvalidFormId {
            get {
                return ResourceManager.GetString("InvalidFormId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid form ordinal: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidFormOrdinal {
            get {
                return ResourceManager.GetString("InvalidFormOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response returned..
        /// </summary>
        internal static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML is not an INPUT control: &apos;{0}&apos;.
        /// </summary>
        internal static string NotAnInputHtmlControl {
            get {
                return ResourceManager.GetString("NotAnInputHtmlControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML is not a SELECT control: &apos;{0}&apos;.
        /// </summary>
        internal static string NotASelectHtmlControl {
            get {
                return ResourceManager.GetString("NotASelectHtmlControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML is not a SELECT OPTION: &apos;{0}&apos;.
        /// </summary>
        internal static string NotASelectHtmlControlOption {
            get {
                return ResourceManager.GetString("NotASelectHtmlControlOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML is not a TEXTAREA control: &apos;{0}&apos;.
        /// </summary>
        internal static string NotATextAreaHtmlControl {
            get {
                return ResourceManager.GetString("NotATextAreaHtmlControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An HTML page was returned unexpectedly..
        /// </summary>
        internal static string UnexpectedHtmlPage {
            get {
                return ResourceManager.GetString("UnexpectedHtmlPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An image was returned unexpectedly..
        /// </summary>
        internal static string UnexpectedImage {
            get {
                return ResourceManager.GetString("UnexpectedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain text was returned unexpectedly..
        /// </summary>
        internal static string UnexpectedPlainText {
            get {
                return ResourceManager.GetString("UnexpectedPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A redirection was returned unexpectedly..
        /// </summary>
        internal static string UnexpectedRedirect {
            get {
                return ResourceManager.GetString("UnexpectedRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response sending request for form page: &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedResponseOnFormPageRequest {
            get {
                return ResourceManager.GetString("UnexpectedResponseOnFormPageRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response submitting form to: &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedResponseOnFormSubmission {
            get {
                return ResourceManager.GetString("UnexpectedResponseOnFormSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml was returned unexpectedly..
        /// </summary>
        internal static string UnexpectedXml {
            get {
                return ResourceManager.GetString("UnexpectedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported HTML control found:&apos;{0}&apos;.
        /// </summary>
        internal static string UnsupportedHtmlControl {
            get {
                return ResourceManager.GetString("UnsupportedHtmlControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported response content type: &apos;{0}&apos;.
        /// </summary>
        internal static string UnsupportedResponseContentType {
            get {
                return ResourceManager.GetString("UnsupportedResponseContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported response type: &apos;{0}&apos;.
        /// </summary>
        internal static string UnsupportedResponseType {
            get {
                return ResourceManager.GetString("UnsupportedResponseType", resourceCulture);
            }
        }
    }
}
