//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NScrape.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NScrape.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;craigslist: account log in&lt;/title&gt;
        ///    &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;//www.craigslist.org/styles/cl.css?v=9baadd40d5c64b557ccd3a5bb8794930&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0, user-scalable=1&quot;&gt;
        ///    &lt;!--[if lt IE 9]&gt;
        ///&lt;script src=&quot;//www.craigslist.org/js/html5shiv.min.js?v=42e8031bc7ca9d67a48f4a5feff7bf29&quot; type=&quot;text/javascript&quot; &gt;&lt;/script&gt;
        ///&lt;![endif]--&gt;
        ///&lt;!--[if lte IE 7]&gt;
        ///&lt;script src=&quot;//www.craigslist.org/js/json2. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string accounts_craigslist_org_login {
            get {
                return ResourceManager.GetString("accounts_craigslist_org_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;craigslist: chicago jobs, apartments, personals, for sale, services, community, and events&lt;/title&gt;
        ///
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;craigslist provides local classifieds and forums for jobs, housing, for sale, personals, services, local community, and events&quot;&gt;
        ///&lt;meta name=&quot;google-site-verification&quot; content=&quot;Ie0Do80edB2EurJYj-bxqMdX7zkMjx_FnjtQp_XMFio&quot;&gt;
        ///&lt;meta name=&quot;msvalidate.01&quot; co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chicago_craigslist_org {
            get {
                return ResourceManager.GetString("chicago_craigslist_org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en-us&quot; class=&quot; styleguide&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Flickr: Advanced Search&lt;/title&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///	&lt;meta name=&quot;description&quot; content=&quot;Flickr is almost certainly the best online photo management and sharing application in the world. Show off your favorite photos and videos to the world, securely and privately show content to your friends and family, or blog the p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string flickr_com_search_advanced {
            get {
                return ResourceManager.GetString("flickr_com_search_advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Comment Box Code&lt;/title&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta property=&quot;fb:admins&quot; content=&quot;1514286275&quot;&gt;
        ///&lt;meta name=&quot;keywords&quot; content=&quot;comment box code, html comment box codes, create, add, scrolling, small, tiny, free, input&quot;&gt;
        ///&lt;meta name=&quot;Description&quot; content=&quot;Create a comment box within your HTML codes.&quot;&gt;
        ///
        ///&lt;link rel=&quot;canonical&quot; href=&quot;http://www.quackit.com/html/codes/comment_box_code.cfm&quot;&gt;
        ///
        ///&lt;link rel=&quot;shortcut icon&quot; href=&quot;http:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quackit_com_html_codes_comment_box_code {
            get {
                return ResourceManager.GetString("quackit_com_html_codes_comment_box_code", resourceCulture);
            }
        }
    }
}
